---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: "2.1.4"
    name: elastic 
  - src: git@github.com:FreeNewMan/kibana-role.git
    scm: git
    version: "0.0.1"
    name: kibana_role
  - src: git@github.com:FreeNewMan/filebeat-role.git
    scm: git
    version: "0.0.1"
    name: filebeat_role         